#pragma once


char* appliances[] = {
	"allen wrenches",
	"gerbil feeders",
	"toilet seats",
	"electric heaters",
	"trash compactors",
	"juice extractor",
	"shower rods and water meters",
	"walkie talkies",
	"copper wires",
	"safety goggles",
	"radial tires",
	"bb pellets",
	"rubber mallets",
	"fans and dehumidifiers",
	"picture hangers",
	"paper cutters",
	"waffle irons",
	"window shutters",
	"paint removers",
	"window louvres",
	"masking tape and plastic gutters",
	"kitchen faucets",
	"folding tables",
	"weather stripping",
	"jumper cables",
	"hooks and tackle",
	"grout and spackle",
	"power foggers",
	"spoons and ladles",
	"pesticides for fumigation",
	"high performance lubrication",
	"metal roofing",
	"water proofing",
	"multi purpose insulation",
	"air compressors",
	"brass connectors",
	"wrecking chisels",
	"smoke detectors",
	"tire gauges",
	"hamster cages",
	"thermostats and bug deflectors",
	"trailer hitch demagnetizers",
	"automatic circumcisers",
	"tennis rackets",
	"angle brackets",
	"duracells and energizers",
	"soffit panels",
	"circuit breakers",
	"vacuum cleaners",
	"coffee makers",
	"calculators",
	"generators",
	"matching salt and pepper shakers"
};